service: web-scraping

provider:
  name: aws
  ecr:
    images:
      selenium-chrome-driver:
        path: ./
  region: us-east-1
  stage: prod

functions:
  scraping:
    image:
      name: selenium-chrome-driver
    events:
      - schedule: cron(*/1 * * * ? *)