service: web-scraping

provider:
  name: aws
  timeout: 30
  ecr:
    images:
      selenium-chrome-driver:
        path: ./
  region: us-east-1

functions:
  scraping:
    image:
      name: selenium-chrome-driver
    # events:
    #   - schedule: cron(*/30 * * * ? *)