service: web-scraping

provider:
  name: aws
  ecr:
    images:
      selenium-chrome-driver:
        path: ./
  region: us-east-1
  stage: prod

functions:
  scraping:
    image:
      name: appimage
    events:
      schedule: cron(*/1 * * * ? *)

plugins:
  - serverless-python-requirements  # Adiciona o plugin de Python para lidar com dependências

# custom:
#   pythonRequirements:
#     dockerizePip: true  # Usar contêiner Docker para instalar dependências nativas se necessário